site_name: Django Wiki
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
  palette:
    scheme: slate
nav:
  - 'Página inicial': index.md
  - Formulários: forms.md
  - Formatadores: formatter.md
  - Modelos: models.md
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences